@file:Suppress("unused")
package ai.platon.cdt.kt.protocol.types.audits

import com.fasterxml.jackson.`annotation`.JsonEnumDefaultValue
import com.fasterxml.jackson.`annotation`.JsonProperty

/**
 * Represents the failure reason when an email verification request fails.
 * Should be updated alongside EmailVerificationRequestResult in
 * third_party/blink/public/mojom/devtools/inspector_issue.mojom.
 */
public enum class EmailVerificationRequestIssueReason {
  @JsonProperty("InvalidEmail")
  INVALID_EMAIL,
  @JsonProperty("DnsFetchFailed")
  DNS_FETCH_FAILED,
  @JsonProperty("DnsInvalidRecord")
  DNS_INVALID_RECORD,
  @JsonProperty("WellKnownHttpNotFound")
  WELL_KNOWN_HTTP_NOT_FOUND,
  @JsonProperty("WellKnownNoResponse")
  WELL_KNOWN_NO_RESPONSE,
  @JsonProperty("WellKnownInvalidResponse")
  WELL_KNOWN_INVALID_RESPONSE,
  @JsonProperty("WellKnownListEmpty")
  WELL_KNOWN_LIST_EMPTY,
  @JsonProperty("WellKnownInvalidContentType")
  WELL_KNOWN_INVALID_CONTENT_TYPE,
  @JsonProperty("WellKnownMissingIssuanceEndpoint")
  WELL_KNOWN_MISSING_ISSUANCE_ENDPOINT,
  @JsonProperty("WellKnownIssuanceEndpointCrossOrigin")
  WELL_KNOWN_ISSUANCE_ENDPOINT_CROSS_ORIGIN,
  @JsonProperty("WellKnownUnsupportedSigningAlgorithm")
  WELL_KNOWN_UNSUPPORTED_SIGNING_ALGORITHM,
  @JsonProperty("TokenHttpNotFound")
  TOKEN_HTTP_NOT_FOUND,
  @JsonProperty("TokenNoResponse")
  TOKEN_NO_RESPONSE,
  @JsonProperty("TokenInvalidResponse")
  TOKEN_INVALID_RESPONSE,
  @JsonProperty("TokenInvalidContentType")
  TOKEN_INVALID_CONTENT_TYPE,
  @JsonProperty("TokenMalformedSdJwt")
  TOKEN_MALFORMED_SD_JWT,
  @JsonProperty("TokenInvalidSdJwt")
  TOKEN_INVALID_SD_JWT,
  @JsonProperty("KeyBindingSigningFailed")
  KEY_BINDING_SIGNING_FAILED,
  @JsonProperty("RpOriginIsOpaque")
  RP_ORIGIN_IS_OPAQUE,
  @JsonProperty("WellKnownMissingAccountsEndpoint")
  WELL_KNOWN_MISSING_ACCOUNTS_ENDPOINT,
  @JsonProperty("UserLoggedOut")
  USER_LOGGED_OUT,
  @JsonProperty("WellKnownAccountsEndpointCrossOrigin")
  WELL_KNOWN_ACCOUNTS_ENDPOINT_CROSS_ORIGIN,
  @JsonProperty("AccountsHttpNotFound")
  ACCOUNTS_HTTP_NOT_FOUND,
  @JsonProperty("AccountsNoResponse")
  ACCOUNTS_NO_RESPONSE,
  @JsonProperty("AccountsInvalidResponse")
  ACCOUNTS_INVALID_RESPONSE,
  @JsonProperty("AccountsInvalidContentType")
  ACCOUNTS_INVALID_CONTENT_TYPE,
  @JsonProperty("AccountsEmptyList")
  ACCOUNTS_EMPTY_LIST,
  @JsonProperty("EmailVerificationWellKnownHttpNotFound")
  EMAIL_VERIFICATION_WELL_KNOWN_HTTP_NOT_FOUND,
  @JsonProperty("EmailVerificationWellKnownNoResponse")
  EMAIL_VERIFICATION_WELL_KNOWN_NO_RESPONSE,
  @JsonProperty("EmailVerificationWellKnownInvalidResponse")
  EMAIL_VERIFICATION_WELL_KNOWN_INVALID_RESPONSE,
  @JsonProperty("EmailVerificationWellKnownInvalidContentType")
  EMAIL_VERIFICATION_WELL_KNOWN_INVALID_CONTENT_TYPE,
  @JsonProperty("JwksHttpNotFound")
  JWKS_HTTP_NOT_FOUND,
  @JsonProperty("JwksInvalidResponse")
  JWKS_INVALID_RESPONSE,
  @JsonProperty("TokenVerificationSdJwtUnsupportedHeaderAlg")
  TOKEN_VERIFICATION_SD_JWT_UNSUPPORTED_HEADER_ALG,
  @JsonProperty("TokenVerificationSdJwtMissingIss")
  TOKEN_VERIFICATION_SD_JWT_MISSING_ISS,
  @JsonProperty("TokenVerificationSdJwtMissingIat")
  TOKEN_VERIFICATION_SD_JWT_MISSING_IAT,
  @JsonProperty("TokenVerificationSdJwtMissingCnf")
  TOKEN_VERIFICATION_SD_JWT_MISSING_CNF,
  @JsonProperty("TokenVerificationSdJwtMissingEmail")
  TOKEN_VERIFICATION_SD_JWT_MISSING_EMAIL,
  @JsonProperty("TokenVerificationSdJwtInvalidIssuedAt")
  TOKEN_VERIFICATION_SD_JWT_INVALID_ISSUED_AT,
  @JsonProperty("TokenVerificationSdJwtInvalidIssuer")
  TOKEN_VERIFICATION_SD_JWT_INVALID_ISSUER,
  @JsonProperty("TokenVerificationSdJwtJwksMissingKeys")
  TOKEN_VERIFICATION_SD_JWT_JWKS_MISSING_KEYS,
  @JsonProperty("TokenVerificationSdJwtSignatureFailed")
  TOKEN_VERIFICATION_SD_JWT_SIGNATURE_FAILED,
  @JsonProperty("TokenVerificationSdJwtInvalidEmailVerified")
  TOKEN_VERIFICATION_SD_JWT_INVALID_EMAIL_VERIFIED,
  @JsonProperty("TokenVerificationSdJwtInvalidEmail")
  TOKEN_VERIFICATION_SD_JWT_INVALID_EMAIL,
  @JsonProperty("TokenVerificationSdJwtInvalidHolderKey")
  TOKEN_VERIFICATION_SD_JWT_INVALID_HOLDER_KEY,
  @JsonProperty("TokenVerificationKbInvalidTyp")
  TOKEN_VERIFICATION_KB_INVALID_TYP,
  @JsonProperty("TokenVerificationKbMissingAud")
  TOKEN_VERIFICATION_KB_MISSING_AUD,
  @JsonProperty("TokenVerificationKbMissingNonce")
  TOKEN_VERIFICATION_KB_MISSING_NONCE,
  @JsonProperty("TokenVerificationKbMissingIat")
  TOKEN_VERIFICATION_KB_MISSING_IAT,
  @JsonProperty("TokenVerificationKbMissingSdHash")
  TOKEN_VERIFICATION_KB_MISSING_SD_HASH,
  @JsonProperty("TokenVerificationKbInvalidIssuedAt")
  TOKEN_VERIFICATION_KB_INVALID_ISSUED_AT,
  @JsonProperty("TokenVerificationKbInvalidAudience")
  TOKEN_VERIFICATION_KB_INVALID_AUDIENCE,
  @JsonProperty("TokenVerificationKbInvalidNonce")
  TOKEN_VERIFICATION_KB_INVALID_NONCE,
  @JsonProperty("TokenVerificationKbInvalidSdHash")
  TOKEN_VERIFICATION_KB_INVALID_SD_HASH,
  @JsonProperty("TokenVerificationKbMissingCnf")
  TOKEN_VERIFICATION_KB_MISSING_CNF,
  @JsonProperty("TokenVerificationKbSignatureFailed")
  TOKEN_VERIFICATION_KB_SIGNATURE_FAILED,
  @JsonEnumDefaultValue
  UNKNOWN,
}
