<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>ai.platon.cdt</groupId>
        <artifactId>cdt-client-root</artifactId>
        <version>4.8.2-SNAPSHOT</version>
    </parent>

    <artifactId>cdt-kotlin-client</artifactId>
    <packaging>jar</packaging>

    <name>cdt-kotlin-client</name>
    <description>Chrome DevTools Kotlin client</description>

    <dependencies>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
        </dependency>
    </dependencies>
</project>
