@file:Suppress("unused")
package ai.platon.cdt.kt.protocol.types.network

import ai.platon.cdt.kt.protocol.support.annotations.Experimental
import com.fasterxml.jackson.`annotation`.JsonProperty
import kotlin.Any
import kotlin.Double
import kotlin.Int
import kotlin.String
import kotlin.collections.Map

/**
 * An object representing a report generated by the Reporting API.
 */
@Experimental
data class ReportingApiReport(
  @param:JsonProperty("id")
  val id: String,
  @param:JsonProperty("initiatorUrl")
  val initiatorUrl: String,
  @param:JsonProperty("destination")
  val destination: String,
  @param:JsonProperty("type")
  val type: String,
  @param:JsonProperty("timestamp")
  val timestamp: Double,
  @param:JsonProperty("depth")
  val depth: Int,
  @param:JsonProperty("completedAttempts")
  val completedAttempts: Int,
  @param:JsonProperty("body")
  val body: Map<String, Any?>,
  @param:JsonProperty("status")
  val status: ReportStatus,
)
