@file:Suppress("unused")
package ai.platon.cdt.kt.serialization.protocol.types.page

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * List of not restored reasons for back-forward cache.
 */
@Serializable
public enum class BackForwardCacheNotRestoredReason {
  @SerialName("NotPrimaryMainFrame")
  NOT_PRIMARY_MAIN_FRAME,
  @SerialName("BackForwardCacheDisabled")
  BACK_FORWARD_CACHE_DISABLED,
  @SerialName("RelatedActiveContentsExist")
  RELATED_ACTIVE_CONTENTS_EXIST,
  @SerialName("HTTPStatusNotOK")
  HTTP_STATUS_NOT_OK,
  @SerialName("SchemeNotHTTPOrHTTPS")
  SCHEME_NOT_HTTP_OR_HTTPS,
  @SerialName("Loading")
  LOADING,
  @SerialName("WasGrantedMediaAccess")
  WAS_GRANTED_MEDIA_ACCESS,
  @SerialName("DisableForRenderFrameHostCalled")
  DISABLE_FOR_RENDER_FRAME_HOST_CALLED,
  @SerialName("DomainNotAllowed")
  DOMAIN_NOT_ALLOWED,
  @SerialName("HTTPMethodNotGET")
  HTTP_METHOD_NOT_GET,
  @SerialName("SubframeIsNavigating")
  SUBFRAME_IS_NAVIGATING,
  @SerialName("Timeout")
  TIMEOUT,
  @SerialName("CacheLimit")
  CACHE_LIMIT,
  @SerialName("JavaScriptExecution")
  JAVA_SCRIPT_EXECUTION,
  @SerialName("RendererProcessKilled")
  RENDERER_PROCESS_KILLED,
  @SerialName("RendererProcessCrashed")
  RENDERER_PROCESS_CRASHED,
  @SerialName("SchedulerTrackedFeatureUsed")
  SCHEDULER_TRACKED_FEATURE_USED,
  @SerialName("ConflictingBrowsingInstance")
  CONFLICTING_BROWSING_INSTANCE,
  @SerialName("CacheFlushed")
  CACHE_FLUSHED,
  @SerialName("ServiceWorkerVersionActivation")
  SERVICE_WORKER_VERSION_ACTIVATION,
  @SerialName("SessionRestored")
  SESSION_RESTORED,
  @SerialName("ServiceWorkerPostMessage")
  SERVICE_WORKER_POST_MESSAGE,
  @SerialName("EnteredBackForwardCacheBeforeServiceWorkerHostAdded")
  ENTERED_BACK_FORWARD_CACHE_BEFORE_SERVICE_WORKER_HOST_ADDED,
  @SerialName("RenderFrameHostReused_SameSite")
  RENDER_FRAME_HOST_REUSED_SAME_SITE,
  @SerialName("RenderFrameHostReused_CrossSite")
  RENDER_FRAME_HOST_REUSED_CROSS_SITE,
  @SerialName("ServiceWorkerClaim")
  SERVICE_WORKER_CLAIM,
  @SerialName("IgnoreEventAndEvict")
  IGNORE_EVENT_AND_EVICT,
  @SerialName("HaveInnerContents")
  HAVE_INNER_CONTENTS,
  @SerialName("TimeoutPuttingInCache")
  TIMEOUT_PUTTING_IN_CACHE,
  @SerialName("BackForwardCacheDisabledByLowMemory")
  BACK_FORWARD_CACHE_DISABLED_BY_LOW_MEMORY,
  @SerialName("BackForwardCacheDisabledByCommandLine")
  BACK_FORWARD_CACHE_DISABLED_BY_COMMAND_LINE,
  @SerialName("NetworkRequestDatapipeDrainedAsBytesConsumer")
  NETWORK_REQUEST_DATAPIPE_DRAINED_AS_BYTES_CONSUMER,
  @SerialName("NetworkRequestRedirected")
  NETWORK_REQUEST_REDIRECTED,
  @SerialName("NetworkRequestTimeout")
  NETWORK_REQUEST_TIMEOUT,
  @SerialName("NetworkExceedsBufferLimit")
  NETWORK_EXCEEDS_BUFFER_LIMIT,
  @SerialName("NavigationCancelledWhileRestoring")
  NAVIGATION_CANCELLED_WHILE_RESTORING,
  @SerialName("NotMostRecentNavigationEntry")
  NOT_MOST_RECENT_NAVIGATION_ENTRY,
  @SerialName("BackForwardCacheDisabledForPrerender")
  BACK_FORWARD_CACHE_DISABLED_FOR_PRERENDER,
  @SerialName("UserAgentOverrideDiffers")
  USER_AGENT_OVERRIDE_DIFFERS,
  @SerialName("ForegroundCacheLimit")
  FOREGROUND_CACHE_LIMIT,
  @SerialName("ForwardCacheDisabled")
  FORWARD_CACHE_DISABLED,
  @SerialName("BrowsingInstanceNotSwapped")
  BROWSING_INSTANCE_NOT_SWAPPED,
  @SerialName("BackForwardCacheDisabledForDelegate")
  BACK_FORWARD_CACHE_DISABLED_FOR_DELEGATE,
  @SerialName("UnloadHandlerExistsInMainFrame")
  UNLOAD_HANDLER_EXISTS_IN_MAIN_FRAME,
  @SerialName("UnloadHandlerExistsInSubFrame")
  UNLOAD_HANDLER_EXISTS_IN_SUB_FRAME,
  @SerialName("ServiceWorkerUnregistration")
  SERVICE_WORKER_UNREGISTRATION,
  @SerialName("CacheControlNoStore")
  CACHE_CONTROL_NO_STORE,
  @SerialName("CacheControlNoStoreCookieModified")
  CACHE_CONTROL_NO_STORE_COOKIE_MODIFIED,
  @SerialName("CacheControlNoStoreHTTPOnlyCookieModified")
  CACHE_CONTROL_NO_STORE_HTTP_ONLY_COOKIE_MODIFIED,
  @SerialName("NoResponseHead")
  NO_RESPONSE_HEAD,
  @SerialName("Unknown")
  UNKNOWN,
  @SerialName("ActivationNavigationsDisallowedForBug1234857")
  ACTIVATION_NAVIGATIONS_DISALLOWED_FOR_BUG_1234857,
  @SerialName("ErrorDocument")
  ERROR_DOCUMENT,
  @SerialName("FencedFramesEmbedder")
  FENCED_FRAMES_EMBEDDER,
  @SerialName("CookieDisabled")
  COOKIE_DISABLED,
  @SerialName("HTTPAuthRequired")
  HTTP_AUTH_REQUIRED,
  @SerialName("CookieFlushed")
  COOKIE_FLUSHED,
  @SerialName("BroadcastChannelOnMessage")
  BROADCAST_CHANNEL_ON_MESSAGE,
  @SerialName("WebViewSettingsChanged")
  WEB_VIEW_SETTINGS_CHANGED,
  @SerialName("WebViewJavaScriptObjectChanged")
  WEB_VIEW_JAVA_SCRIPT_OBJECT_CHANGED,
  @SerialName("WebViewMessageListenerInjected")
  WEB_VIEW_MESSAGE_LISTENER_INJECTED,
  @SerialName("WebViewSafeBrowsingAllowlistChanged")
  WEB_VIEW_SAFE_BROWSING_ALLOWLIST_CHANGED,
  @SerialName("WebViewDocumentStartJavascriptChanged")
  WEB_VIEW_DOCUMENT_START_JAVASCRIPT_CHANGED,
  @SerialName("WebSocket")
  WEB_SOCKET,
  @SerialName("WebTransport")
  WEB_TRANSPORT,
  @SerialName("WebRTC")
  WEB_RTC,
  @SerialName("MainResourceHasCacheControlNoStore")
  MAIN_RESOURCE_HAS_CACHE_CONTROL_NO_STORE,
  @SerialName("MainResourceHasCacheControlNoCache")
  MAIN_RESOURCE_HAS_CACHE_CONTROL_NO_CACHE,
  @SerialName("SubresourceHasCacheControlNoStore")
  SUBRESOURCE_HAS_CACHE_CONTROL_NO_STORE,
  @SerialName("SubresourceHasCacheControlNoCache")
  SUBRESOURCE_HAS_CACHE_CONTROL_NO_CACHE,
  @SerialName("ContainsPlugins")
  CONTAINS_PLUGINS,
  @SerialName("DocumentLoaded")
  DOCUMENT_LOADED,
  @SerialName("OutstandingNetworkRequestOthers")
  OUTSTANDING_NETWORK_REQUEST_OTHERS,
  @SerialName("RequestedMIDIPermission")
  REQUESTED_MIDI_PERMISSION,
  @SerialName("RequestedAudioCapturePermission")
  REQUESTED_AUDIO_CAPTURE_PERMISSION,
  @SerialName("RequestedVideoCapturePermission")
  REQUESTED_VIDEO_CAPTURE_PERMISSION,
  @SerialName("RequestedBackForwardCacheBlockedSensors")
  REQUESTED_BACK_FORWARD_CACHE_BLOCKED_SENSORS,
  @SerialName("RequestedBackgroundWorkPermission")
  REQUESTED_BACKGROUND_WORK_PERMISSION,
  @SerialName("BroadcastChannel")
  BROADCAST_CHANNEL,
  @SerialName("WebXR")
  WEB_XR,
  @SerialName("SharedWorker")
  SHARED_WORKER,
  @SerialName("SharedWorkerMessage")
  SHARED_WORKER_MESSAGE,
  @SerialName("SharedWorkerWithNoActiveClient")
  SHARED_WORKER_WITH_NO_ACTIVE_CLIENT,
  @SerialName("WebLocks")
  WEB_LOCKS,
  @SerialName("WebLocksContention")
  WEB_LOCKS_CONTENTION,
  @SerialName("WebHID")
  WEB_HID,
  @SerialName("WebBluetooth")
  WEB_BLUETOOTH,
  @SerialName("WebShare")
  WEB_SHARE,
  @SerialName("RequestedStorageAccessGrant")
  REQUESTED_STORAGE_ACCESS_GRANT,
  @SerialName("WebNfc")
  WEB_NFC,
  @SerialName("OutstandingNetworkRequestFetch")
  OUTSTANDING_NETWORK_REQUEST_FETCH,
  @SerialName("OutstandingNetworkRequestXHR")
  OUTSTANDING_NETWORK_REQUEST_XHR,
  @SerialName("AppBanner")
  APP_BANNER,
  @SerialName("Printing")
  PRINTING,
  @SerialName("WebDatabase")
  WEB_DATABASE,
  @SerialName("PictureInPicture")
  PICTURE_IN_PICTURE,
  @SerialName("SpeechRecognizer")
  SPEECH_RECOGNIZER,
  @SerialName("IdleManager")
  IDLE_MANAGER,
  @SerialName("PaymentManager")
  PAYMENT_MANAGER,
  @SerialName("SpeechSynthesis")
  SPEECH_SYNTHESIS,
  @SerialName("KeyboardLock")
  KEYBOARD_LOCK,
  @SerialName("WebOTPService")
  WEB_OTP_SERVICE,
  @SerialName("OutstandingNetworkRequestDirectSocket")
  OUTSTANDING_NETWORK_REQUEST_DIRECT_SOCKET,
  @SerialName("InjectedJavascript")
  INJECTED_JAVASCRIPT,
  @SerialName("InjectedStyleSheet")
  INJECTED_STYLE_SHEET,
  @SerialName("KeepaliveRequest")
  KEEPALIVE_REQUEST,
  @SerialName("IndexedDBEvent")
  INDEXED_DB_EVENT,
  @SerialName("Dummy")
  DUMMY,
  @SerialName("JsNetworkRequestReceivedCacheControlNoStoreResource")
  JS_NETWORK_REQUEST_RECEIVED_CACHE_CONTROL_NO_STORE_RESOURCE,
  @SerialName("WebRTCUsedWithCCNS")
  WEB_RTC_USED_WITH_CCNS,
  @SerialName("WebTransportUsedWithCCNS")
  WEB_TRANSPORT_USED_WITH_CCNS,
  @SerialName("WebSocketUsedWithCCNS")
  WEB_SOCKET_USED_WITH_CCNS,
  @SerialName("SmartCard")
  SMART_CARD,
  @SerialName("LiveMediaStreamTrack")
  LIVE_MEDIA_STREAM_TRACK,
  @SerialName("UnloadHandler")
  UNLOAD_HANDLER,
  @SerialName("ParserAborted")
  PARSER_ABORTED,
  @SerialName("ContentSecurityHandler")
  CONTENT_SECURITY_HANDLER,
  @SerialName("ContentWebAuthenticationAPI")
  CONTENT_WEB_AUTHENTICATION_API,
  @SerialName("ContentFileChooser")
  CONTENT_FILE_CHOOSER,
  @SerialName("ContentSerial")
  CONTENT_SERIAL,
  @SerialName("ContentFileSystemAccess")
  CONTENT_FILE_SYSTEM_ACCESS,
  @SerialName("ContentMediaDevicesDispatcherHost")
  CONTENT_MEDIA_DEVICES_DISPATCHER_HOST,
  @SerialName("ContentWebBluetooth")
  CONTENT_WEB_BLUETOOTH,
  @SerialName("ContentWebUSB")
  CONTENT_WEB_USB,
  @SerialName("ContentMediaSessionService")
  CONTENT_MEDIA_SESSION_SERVICE,
  @SerialName("ContentScreenReader")
  CONTENT_SCREEN_READER,
  @SerialName("ContentDiscarded")
  CONTENT_DISCARDED,
  @SerialName("EmbedderPopupBlockerTabHelper")
  EMBEDDER_POPUP_BLOCKER_TAB_HELPER,
  @SerialName("EmbedderSafeBrowsingTriggeredPopupBlocker")
  EMBEDDER_SAFE_BROWSING_TRIGGERED_POPUP_BLOCKER,
  @SerialName("EmbedderSafeBrowsingThreatDetails")
  EMBEDDER_SAFE_BROWSING_THREAT_DETAILS,
  @SerialName("EmbedderAppBannerManager")
  EMBEDDER_APP_BANNER_MANAGER,
  @SerialName("EmbedderDomDistillerViewerSource")
  EMBEDDER_DOM_DISTILLER_VIEWER_SOURCE,
  @SerialName("EmbedderDomDistillerSelfDeletingRequestDelegate")
  EMBEDDER_DOM_DISTILLER_SELF_DELETING_REQUEST_DELEGATE,
  @SerialName("EmbedderOomInterventionTabHelper")
  EMBEDDER_OOM_INTERVENTION_TAB_HELPER,
  @SerialName("EmbedderOfflinePage")
  EMBEDDER_OFFLINE_PAGE,
  @SerialName("EmbedderChromePasswordManagerClientBindCredentialManager")
  EMBEDDER_CHROME_PASSWORD_MANAGER_CLIENT_BIND_CREDENTIAL_MANAGER,
  @SerialName("EmbedderPermissionRequestManager")
  EMBEDDER_PERMISSION_REQUEST_MANAGER,
  @SerialName("EmbedderModalDialog")
  EMBEDDER_MODAL_DIALOG,
  @SerialName("EmbedderExtensions")
  EMBEDDER_EXTENSIONS,
  @SerialName("EmbedderExtensionMessaging")
  EMBEDDER_EXTENSION_MESSAGING,
  @SerialName("EmbedderExtensionMessagingForOpenPort")
  EMBEDDER_EXTENSION_MESSAGING_FOR_OPEN_PORT,
  @SerialName("EmbedderExtensionSentMessageToCachedFrame")
  EMBEDDER_EXTENSION_SENT_MESSAGE_TO_CACHED_FRAME,
  @SerialName("EmbedderExtensionFrame")
  EMBEDDER_EXTENSION_FRAME,
  @SerialName("RequestedByWebViewClient")
  REQUESTED_BY_WEB_VIEW_CLIENT,
  @SerialName("PostMessageByWebViewClient")
  POST_MESSAGE_BY_WEB_VIEW_CLIENT,
  @SerialName("CacheControlNoStoreDeviceBoundSessionTerminated")
  CACHE_CONTROL_NO_STORE_DEVICE_BOUND_SESSION_TERMINATED,
  @SerialName("CacheLimitPrunedOnModerateMemoryPressure")
  CACHE_LIMIT_PRUNED_ON_MODERATE_MEMORY_PRESSURE,
  @SerialName("CacheLimitPrunedOnCriticalMemoryPressure")
  CACHE_LIMIT_PRUNED_ON_CRITICAL_MEMORY_PRESSURE,
}
