@file:Suppress("unused")
package ai.platon.cdt.kt.serialization.protocol.types.page

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * All Permissions Policy features. This enum should match the one defined
 * in renderer/core/feature_policy/feature_policy_features.json5.
 */
@Serializable
public enum class PermissionsPolicyFeature {
  @SerialName("accelerometer")
  ACCELEROMETER,
  @SerialName("ambient-light-sensor")
  AMBIENT_LIGHT_SENSOR,
  @SerialName("autoplay")
  AUTOPLAY,
  @SerialName("camera")
  CAMERA,
  @SerialName("ch-dpr")
  CH_DPR,
  @SerialName("ch-device-memory")
  CH_DEVICE_MEMORY,
  @SerialName("ch-downlink")
  CH_DOWNLINK,
  @SerialName("ch-ect")
  CH_ECT,
  @SerialName("ch-lang")
  CH_LANG,
  @SerialName("ch-rtt")
  CH_RTT,
  @SerialName("ch-ua")
  CH_UA,
  @SerialName("ch-ua-arch")
  CH_UA_ARCH,
  @SerialName("ch-ua-platform")
  CH_UA_PLATFORM,
  @SerialName("ch-ua-model")
  CH_UA_MODEL,
  @SerialName("ch-ua-mobile")
  CH_UA_MOBILE,
  @SerialName("ch-ua-full-version")
  CH_UA_FULL_VERSION,
  @SerialName("ch-ua-platform-version")
  CH_UA_PLATFORM_VERSION,
  @SerialName("ch-viewport-width")
  CH_VIEWPORT_WIDTH,
  @SerialName("ch-width")
  CH_WIDTH,
  @SerialName("clipboard-read")
  CLIPBOARD_READ,
  @SerialName("clipboard-write")
  CLIPBOARD_WRITE,
  @SerialName("conversion-measurement")
  CONVERSION_MEASUREMENT,
  @SerialName("cross-origin-isolated")
  CROSS_ORIGIN_ISOLATED,
  @SerialName("display-capture")
  DISPLAY_CAPTURE,
  @SerialName("document-domain")
  DOCUMENT_DOMAIN,
  @SerialName("encrypted-media")
  ENCRYPTED_MEDIA,
  @SerialName("execution-while-out-of-viewport")
  EXECUTION_WHILE_OUT_OF_VIEWPORT,
  @SerialName("execution-while-not-rendered")
  EXECUTION_WHILE_NOT_RENDERED,
  @SerialName("focus-without-user-activation")
  FOCUS_WITHOUT_USER_ACTIVATION,
  @SerialName("fullscreen")
  FULLSCREEN,
  @SerialName("frobulate")
  FROBULATE,
  @SerialName("gamepad")
  GAMEPAD,
  @SerialName("geolocation")
  GEOLOCATION,
  @SerialName("gyroscope")
  GYROSCOPE,
  @SerialName("hid")
  HID,
  @SerialName("idle-detection")
  IDLE_DETECTION,
  @SerialName("interest-cohort")
  INTEREST_COHORT,
  @SerialName("magnetometer")
  MAGNETOMETER,
  @SerialName("microphone")
  MICROPHONE,
  @SerialName("midi")
  MIDI,
  @SerialName("otp-credentials")
  OTP_CREDENTIALS,
  @SerialName("payment")
  PAYMENT,
  @SerialName("picture-in-picture")
  PICTURE_IN_PICTURE,
  @SerialName("publickey-credentials-get")
  PUBLICKEY_CREDENTIALS_GET,
  @SerialName("screen-wake-lock")
  SCREEN_WAKE_LOCK,
  @SerialName("serial")
  SERIAL,
  @SerialName("storage-access-api")
  STORAGE_ACCESS_API,
  @SerialName("sync-xhr")
  SYNC_XHR,
  @SerialName("trust-token-redemption")
  TRUST_TOKEN_REDEMPTION,
  @SerialName("usb")
  USB,
  @SerialName("vertical-scroll")
  VERTICAL_SCROLL,
  @SerialName("web-share")
  WEB_SHARE,
  @SerialName("xr-spatial-tracking")
  XR_SPATIAL_TRACKING,
  UNKNOWN,
}
