<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>ai.platon.cdt</groupId>
        <artifactId>cdt-client-root</artifactId>
        <version>4.8.2-SNAPSHOT</version>
    </parent>

    <artifactId>cdt-kotlin-client-serialization</artifactId>

    <name>cdt-kotlin-client-serialization</name>
    <description>Chrome DevTools Kotlin client with kotlinx.serialization support</description>

    <dependencies>
        <dependency>
            <groupId>org.jetbrains.kotlinx</groupId>
            <artifactId>kotlinx-serialization-json</artifactId>
        </dependency>
    </dependencies>
</project>
