@file:Suppress("unused")
package ai.platon.cdt.kt.serialization.protocol.types.browser

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public enum class PermissionType {
  @SerialName("ar")
  AR,
  @SerialName("audioCapture")
  AUDIO_CAPTURE,
  @SerialName("automaticFullscreen")
  AUTOMATIC_FULLSCREEN,
  @SerialName("backgroundFetch")
  BACKGROUND_FETCH,
  @SerialName("backgroundSync")
  BACKGROUND_SYNC,
  @SerialName("cameraPanTiltZoom")
  CAMERA_PAN_TILT_ZOOM,
  @SerialName("capturedSurfaceControl")
  CAPTURED_SURFACE_CONTROL,
  @SerialName("clipboardReadWrite")
  CLIPBOARD_READ_WRITE,
  @SerialName("clipboardSanitizedWrite")
  CLIPBOARD_SANITIZED_WRITE,
  @SerialName("displayCapture")
  DISPLAY_CAPTURE,
  @SerialName("durableStorage")
  DURABLE_STORAGE,
  @SerialName("geolocation")
  GEOLOCATION,
  @SerialName("handTracking")
  HAND_TRACKING,
  @SerialName("idleDetection")
  IDLE_DETECTION,
  @SerialName("keyboardLock")
  KEYBOARD_LOCK,
  @SerialName("localFonts")
  LOCAL_FONTS,
  @SerialName("localNetwork")
  LOCAL_NETWORK,
  @SerialName("localNetworkAccess")
  LOCAL_NETWORK_ACCESS,
  @SerialName("loopbackNetwork")
  LOOPBACK_NETWORK,
  @SerialName("midi")
  MIDI,
  @SerialName("midiSysex")
  MIDI_SYSEX,
  @SerialName("nfc")
  NFC,
  @SerialName("notifications")
  NOTIFICATIONS,
  @SerialName("paymentHandler")
  PAYMENT_HANDLER,
  @SerialName("periodicBackgroundSync")
  PERIODIC_BACKGROUND_SYNC,
  @SerialName("pointerLock")
  POINTER_LOCK,
  @SerialName("protectedMediaIdentifier")
  PROTECTED_MEDIA_IDENTIFIER,
  @SerialName("sensors")
  SENSORS,
  @SerialName("smartCard")
  SMART_CARD,
  @SerialName("speakerSelection")
  SPEAKER_SELECTION,
  @SerialName("storageAccess")
  STORAGE_ACCESS,
  @SerialName("topLevelStorageAccess")
  TOP_LEVEL_STORAGE_ACCESS,
  @SerialName("videoCapture")
  VIDEO_CAPTURE,
  @SerialName("vr")
  VR,
  @SerialName("wakeLockScreen")
  WAKE_LOCK_SCREEN,
  @SerialName("wakeLockSystem")
  WAKE_LOCK_SYSTEM,
  @SerialName("webAppInstallation")
  WEB_APP_INSTALLATION,
  @SerialName("webPrinting")
  WEB_PRINTING,
  @SerialName("windowManagement")
  WINDOW_MANAGEMENT,
  UNKNOWN,
}
