@file:Suppress("unused")
package ai.platon.cdt.kt.serialization.protocol.types.preload

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * List of FinalStatus reasons for Prerender2.
 */
@Serializable
public enum class PrerenderFinalStatus {
  @SerialName("Activated")
  ACTIVATED,
  @SerialName("Destroyed")
  DESTROYED,
  @SerialName("LowEndDevice")
  LOW_END_DEVICE,
  @SerialName("InvalidSchemeRedirect")
  INVALID_SCHEME_REDIRECT,
  @SerialName("InvalidSchemeNavigation")
  INVALID_SCHEME_NAVIGATION,
  @SerialName("NavigationRequestBlockedByCsp")
  NAVIGATION_REQUEST_BLOCKED_BY_CSP,
  @SerialName("MojoBinderPolicy")
  MOJO_BINDER_POLICY,
  @SerialName("RendererProcessCrashed")
  RENDERER_PROCESS_CRASHED,
  @SerialName("RendererProcessKilled")
  RENDERER_PROCESS_KILLED,
  @SerialName("Download")
  DOWNLOAD,
  @SerialName("TriggerDestroyed")
  TRIGGER_DESTROYED,
  @SerialName("NavigationNotCommitted")
  NAVIGATION_NOT_COMMITTED,
  @SerialName("NavigationBadHttpStatus")
  NAVIGATION_BAD_HTTP_STATUS,
  @SerialName("ClientCertRequested")
  CLIENT_CERT_REQUESTED,
  @SerialName("NavigationRequestNetworkError")
  NAVIGATION_REQUEST_NETWORK_ERROR,
  @SerialName("CancelAllHostsForTesting")
  CANCEL_ALL_HOSTS_FOR_TESTING,
  @SerialName("DidFailLoad")
  DID_FAIL_LOAD,
  @SerialName("Stop")
  STOP,
  @SerialName("SslCertificateError")
  SSL_CERTIFICATE_ERROR,
  @SerialName("LoginAuthRequested")
  LOGIN_AUTH_REQUESTED,
  @SerialName("UaChangeRequiresReload")
  UA_CHANGE_REQUIRES_RELOAD,
  @SerialName("BlockedByClient")
  BLOCKED_BY_CLIENT,
  @SerialName("AudioOutputDeviceRequested")
  AUDIO_OUTPUT_DEVICE_REQUESTED,
  @SerialName("MixedContent")
  MIXED_CONTENT,
  @SerialName("TriggerBackgrounded")
  TRIGGER_BACKGROUNDED,
  @SerialName("MemoryLimitExceeded")
  MEMORY_LIMIT_EXCEEDED,
  @SerialName("DataSaverEnabled")
  DATA_SAVER_ENABLED,
  @SerialName("TriggerUrlHasEffectiveUrl")
  TRIGGER_URL_HAS_EFFECTIVE_URL,
  @SerialName("ActivatedBeforeStarted")
  ACTIVATED_BEFORE_STARTED,
  @SerialName("InactivePageRestriction")
  INACTIVE_PAGE_RESTRICTION,
  @SerialName("StartFailed")
  START_FAILED,
  @SerialName("TimeoutBackgrounded")
  TIMEOUT_BACKGROUNDED,
  @SerialName("CrossSiteRedirectInInitialNavigation")
  CROSS_SITE_REDIRECT_IN_INITIAL_NAVIGATION,
  @SerialName("CrossSiteNavigationInInitialNavigation")
  CROSS_SITE_NAVIGATION_IN_INITIAL_NAVIGATION,
  @SerialName("SameSiteCrossOriginRedirectNotOptInInInitialNavigation")
  SAME_SITE_CROSS_ORIGIN_REDIRECT_NOT_OPT_IN_IN_INITIAL_NAVIGATION,
  @SerialName("SameSiteCrossOriginNavigationNotOptInInInitialNavigation")
  SAME_SITE_CROSS_ORIGIN_NAVIGATION_NOT_OPT_IN_IN_INITIAL_NAVIGATION,
  @SerialName("ActivationNavigationParameterMismatch")
  ACTIVATION_NAVIGATION_PARAMETER_MISMATCH,
  @SerialName("ActivatedInBackground")
  ACTIVATED_IN_BACKGROUND,
  @SerialName("EmbedderHostDisallowed")
  EMBEDDER_HOST_DISALLOWED,
  @SerialName("ActivationNavigationDestroyedBeforeSuccess")
  ACTIVATION_NAVIGATION_DESTROYED_BEFORE_SUCCESS,
  @SerialName("TabClosedByUserGesture")
  TAB_CLOSED_BY_USER_GESTURE,
  @SerialName("TabClosedWithoutUserGesture")
  TAB_CLOSED_WITHOUT_USER_GESTURE,
  @SerialName("PrimaryMainFrameRendererProcessCrashed")
  PRIMARY_MAIN_FRAME_RENDERER_PROCESS_CRASHED,
  @SerialName("PrimaryMainFrameRendererProcessKilled")
  PRIMARY_MAIN_FRAME_RENDERER_PROCESS_KILLED,
  @SerialName("ActivationFramePolicyNotCompatible")
  ACTIVATION_FRAME_POLICY_NOT_COMPATIBLE,
  @SerialName("PreloadingDisabled")
  PRELOADING_DISABLED,
  @SerialName("BatterySaverEnabled")
  BATTERY_SAVER_ENABLED,
  @SerialName("ActivatedDuringMainFrameNavigation")
  ACTIVATED_DURING_MAIN_FRAME_NAVIGATION,
  @SerialName("PreloadingUnsupportedByWebContents")
  PRELOADING_UNSUPPORTED_BY_WEB_CONTENTS,
  @SerialName("CrossSiteRedirectInMainFrameNavigation")
  CROSS_SITE_REDIRECT_IN_MAIN_FRAME_NAVIGATION,
  @SerialName("CrossSiteNavigationInMainFrameNavigation")
  CROSS_SITE_NAVIGATION_IN_MAIN_FRAME_NAVIGATION,
  @SerialName("SameSiteCrossOriginRedirectNotOptInInMainFrameNavigation")
  SAME_SITE_CROSS_ORIGIN_REDIRECT_NOT_OPT_IN_IN_MAIN_FRAME_NAVIGATION,
  @SerialName("SameSiteCrossOriginNavigationNotOptInInMainFrameNavigation")
  SAME_SITE_CROSS_ORIGIN_NAVIGATION_NOT_OPT_IN_IN_MAIN_FRAME_NAVIGATION,
  @SerialName("MemoryPressureOnTrigger")
  MEMORY_PRESSURE_ON_TRIGGER,
  @SerialName("MemoryPressureAfterTriggered")
  MEMORY_PRESSURE_AFTER_TRIGGERED,
  @SerialName("PrerenderingDisabledByDevTools")
  PRERENDERING_DISABLED_BY_DEV_TOOLS,
  @SerialName("SpeculationRuleRemoved")
  SPECULATION_RULE_REMOVED,
  @SerialName("ActivatedWithAuxiliaryBrowsingContexts")
  ACTIVATED_WITH_AUXILIARY_BROWSING_CONTEXTS,
  @SerialName("MaxNumOfRunningEagerPrerendersExceeded")
  MAX_NUM_OF_RUNNING_EAGER_PRERENDERS_EXCEEDED,
  @SerialName("MaxNumOfRunningNonEagerPrerendersExceeded")
  MAX_NUM_OF_RUNNING_NON_EAGER_PRERENDERS_EXCEEDED,
  @SerialName("MaxNumOfRunningEmbedderPrerendersExceeded")
  MAX_NUM_OF_RUNNING_EMBEDDER_PRERENDERS_EXCEEDED,
  @SerialName("PrerenderingUrlHasEffectiveUrl")
  PRERENDERING_URL_HAS_EFFECTIVE_URL,
  @SerialName("RedirectedPrerenderingUrlHasEffectiveUrl")
  REDIRECTED_PRERENDERING_URL_HAS_EFFECTIVE_URL,
  @SerialName("ActivationUrlHasEffectiveUrl")
  ACTIVATION_URL_HAS_EFFECTIVE_URL,
  @SerialName("JavaScriptInterfaceAdded")
  JAVA_SCRIPT_INTERFACE_ADDED,
  @SerialName("JavaScriptInterfaceRemoved")
  JAVA_SCRIPT_INTERFACE_REMOVED,
  @SerialName("AllPrerenderingCanceled")
  ALL_PRERENDERING_CANCELED,
  @SerialName("WindowClosed")
  WINDOW_CLOSED,
  @SerialName("SlowNetwork")
  SLOW_NETWORK,
  @SerialName("OtherPrerenderedPageActivated")
  OTHER_PRERENDERED_PAGE_ACTIVATED,
  @SerialName("V8OptimizerDisabled")
  V_8OPTIMIZER_DISABLED,
  @SerialName("PrerenderFailedDuringPrefetch")
  PRERENDER_FAILED_DURING_PREFETCH,
  @SerialName("BrowsingDataRemoved")
  BROWSING_DATA_REMOVED,
  @SerialName("PrerenderHostReused")
  PRERENDER_HOST_REUSED,
  @SerialName("FormSubmitWhenPrerendering")
  FORM_SUBMIT_WHEN_PRERENDERING,
  @SerialName("CrossDocumentRestart")
  CROSS_DOCUMENT_RESTART,
  UNKNOWN,
}
