@file:Suppress("unused")
package ai.platon.cdt.kt.serialization.protocol.types.network

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * A fetch result for a device bound session creation or refresh.
 */
@Serializable
public enum class DeviceBoundSessionFetchResult {
  @SerialName("Success")
  SUCCESS,
  @SerialName("KeyError")
  KEY_ERROR,
  @SerialName("SigningError")
  SIGNING_ERROR,
  @SerialName("TransientSigningError")
  TRANSIENT_SIGNING_ERROR,
  @SerialName("ServerRequestedTermination")
  SERVER_REQUESTED_TERMINATION,
  @SerialName("InvalidSessionId")
  INVALID_SESSION_ID,
  @SerialName("InvalidChallenge")
  INVALID_CHALLENGE,
  @SerialName("TooManyChallenges")
  TOO_MANY_CHALLENGES,
  @SerialName("InvalidFetcherUrl")
  INVALID_FETCHER_URL,
  @SerialName("InvalidRefreshUrl")
  INVALID_REFRESH_URL,
  @SerialName("TransientHttpError")
  TRANSIENT_HTTP_ERROR,
  @SerialName("ScopeOriginSameSiteMismatch")
  SCOPE_ORIGIN_SAME_SITE_MISMATCH,
  @SerialName("RefreshUrlSameSiteMismatch")
  REFRESH_URL_SAME_SITE_MISMATCH,
  @SerialName("MismatchedSessionId")
  MISMATCHED_SESSION_ID,
  @SerialName("MissingScope")
  MISSING_SCOPE,
  @SerialName("NoCredentials")
  NO_CREDENTIALS,
  @SerialName("SubdomainRegistrationWellKnownUnavailable")
  SUBDOMAIN_REGISTRATION_WELL_KNOWN_UNAVAILABLE,
  @SerialName("SubdomainRegistrationUnauthorized")
  SUBDOMAIN_REGISTRATION_UNAUTHORIZED,
  @SerialName("SubdomainRegistrationWellKnownMalformed")
  SUBDOMAIN_REGISTRATION_WELL_KNOWN_MALFORMED,
  @SerialName("SessionProviderWellKnownUnavailable")
  SESSION_PROVIDER_WELL_KNOWN_UNAVAILABLE,
  @SerialName("RelyingPartyWellKnownUnavailable")
  RELYING_PARTY_WELL_KNOWN_UNAVAILABLE,
  @SerialName("FederatedKeyThumbprintMismatch")
  FEDERATED_KEY_THUMBPRINT_MISMATCH,
  @SerialName("InvalidFederatedSessionUrl")
  INVALID_FEDERATED_SESSION_URL,
  @SerialName("InvalidFederatedKey")
  INVALID_FEDERATED_KEY,
  @SerialName("TooManyRelyingOriginLabels")
  TOO_MANY_RELYING_ORIGIN_LABELS,
  @SerialName("BoundCookieSetForbidden")
  BOUND_COOKIE_SET_FORBIDDEN,
  @SerialName("NetError")
  NET_ERROR,
  @SerialName("ProxyError")
  PROXY_ERROR,
  @SerialName("EmptySessionConfig")
  EMPTY_SESSION_CONFIG,
  @SerialName("InvalidCredentialsConfig")
  INVALID_CREDENTIALS_CONFIG,
  @SerialName("InvalidCredentialsType")
  INVALID_CREDENTIALS_TYPE,
  @SerialName("InvalidCredentialsEmptyName")
  INVALID_CREDENTIALS_EMPTY_NAME,
  @SerialName("InvalidCredentialsCookie")
  INVALID_CREDENTIALS_COOKIE,
  @SerialName("PersistentHttpError")
  PERSISTENT_HTTP_ERROR,
  @SerialName("RegistrationAttemptedChallenge")
  REGISTRATION_ATTEMPTED_CHALLENGE,
  @SerialName("InvalidScopeOrigin")
  INVALID_SCOPE_ORIGIN,
  @SerialName("ScopeOriginContainsPath")
  SCOPE_ORIGIN_CONTAINS_PATH,
  @SerialName("RefreshInitiatorNotString")
  REFRESH_INITIATOR_NOT_STRING,
  @SerialName("RefreshInitiatorInvalidHostPattern")
  REFRESH_INITIATOR_INVALID_HOST_PATTERN,
  @SerialName("InvalidScopeSpecification")
  INVALID_SCOPE_SPECIFICATION,
  @SerialName("MissingScopeSpecificationType")
  MISSING_SCOPE_SPECIFICATION_TYPE,
  @SerialName("EmptyScopeSpecificationDomain")
  EMPTY_SCOPE_SPECIFICATION_DOMAIN,
  @SerialName("EmptyScopeSpecificationPath")
  EMPTY_SCOPE_SPECIFICATION_PATH,
  @SerialName("InvalidScopeSpecificationType")
  INVALID_SCOPE_SPECIFICATION_TYPE,
  @SerialName("InvalidScopeIncludeSite")
  INVALID_SCOPE_INCLUDE_SITE,
  @SerialName("MissingScopeIncludeSite")
  MISSING_SCOPE_INCLUDE_SITE,
  @SerialName("FederatedNotAuthorizedByProvider")
  FEDERATED_NOT_AUTHORIZED_BY_PROVIDER,
  @SerialName("FederatedNotAuthorizedByRelyingParty")
  FEDERATED_NOT_AUTHORIZED_BY_RELYING_PARTY,
  @SerialName("SessionProviderWellKnownMalformed")
  SESSION_PROVIDER_WELL_KNOWN_MALFORMED,
  @SerialName("SessionProviderWellKnownHasProviderOrigin")
  SESSION_PROVIDER_WELL_KNOWN_HAS_PROVIDER_ORIGIN,
  @SerialName("RelyingPartyWellKnownMalformed")
  RELYING_PARTY_WELL_KNOWN_MALFORMED,
  @SerialName("RelyingPartyWellKnownHasRelyingOrigins")
  RELYING_PARTY_WELL_KNOWN_HAS_RELYING_ORIGINS,
  @SerialName("InvalidFederatedSessionProviderSessionMissing")
  INVALID_FEDERATED_SESSION_PROVIDER_SESSION_MISSING,
  @SerialName("InvalidFederatedSessionWrongProviderOrigin")
  INVALID_FEDERATED_SESSION_WRONG_PROVIDER_ORIGIN,
  @SerialName("InvalidCredentialsCookieCreationTime")
  INVALID_CREDENTIALS_COOKIE_CREATION_TIME,
  @SerialName("InvalidCredentialsCookieName")
  INVALID_CREDENTIALS_COOKIE_NAME,
  @SerialName("InvalidCredentialsCookieParsing")
  INVALID_CREDENTIALS_COOKIE_PARSING,
  @SerialName("InvalidCredentialsCookieUnpermittedAttribute")
  INVALID_CREDENTIALS_COOKIE_UNPERMITTED_ATTRIBUTE,
  @SerialName("InvalidCredentialsCookieInvalidDomain")
  INVALID_CREDENTIALS_COOKIE_INVALID_DOMAIN,
  @SerialName("InvalidCredentialsCookiePrefix")
  INVALID_CREDENTIALS_COOKIE_PREFIX,
  @SerialName("InvalidScopeRulePath")
  INVALID_SCOPE_RULE_PATH,
  @SerialName("InvalidScopeRuleHostPattern")
  INVALID_SCOPE_RULE_HOST_PATTERN,
  @SerialName("ScopeRuleOriginScopedHostPatternMismatch")
  SCOPE_RULE_ORIGIN_SCOPED_HOST_PATTERN_MISMATCH,
  @SerialName("ScopeRuleSiteScopedHostPatternMismatch")
  SCOPE_RULE_SITE_SCOPED_HOST_PATTERN_MISMATCH,
  @SerialName("SigningQuotaExceeded")
  SIGNING_QUOTA_EXCEEDED,
  @SerialName("InvalidConfigJson")
  INVALID_CONFIG_JSON,
  @SerialName("InvalidFederatedSessionProviderFailedToRestoreKey")
  INVALID_FEDERATED_SESSION_PROVIDER_FAILED_TO_RESTORE_KEY,
  @SerialName("FailedToUnwrapKey")
  FAILED_TO_UNWRAP_KEY,
  @SerialName("SessionDeletedDuringRefresh")
  SESSION_DELETED_DURING_REFRESH,
  @SerialName("CrossOriginRegistrationSiteNotIncluded")
  CROSS_ORIGIN_REGISTRATION_SITE_NOT_INCLUDED,
  UNKNOWN,
}
