@file:Suppress("unused")
package ai.platon.cdt.kt.serialization.protocol.types.network

import ai.platon.cdt.kt.serialization.protocol.support.annotations.Experimental
import kotlin.Double
import kotlin.Int
import kotlin.String
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonObject

/**
 * An object representing a report generated by the Reporting API.
 */
@Serializable
@Experimental
data class ReportingApiReport(
  @property:SerialName("id")
  val id: String,
  @property:SerialName("initiatorUrl")
  val initiatorUrl: String,
  @property:SerialName("destination")
  val destination: String,
  @property:SerialName("type")
  val type: String,
  @property:SerialName("timestamp")
  val timestamp: Double,
  @property:SerialName("depth")
  val depth: Int,
  @property:SerialName("completedAttempts")
  val completedAttempts: Int,
  @property:SerialName("body")
  val body: JsonObject?,
  @property:SerialName("status")
  val status: ReportStatus,
)
