@file:Suppress("unused")
package ai.platon.cdt.kt.serialization.protocol.types.audits

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Represents the failure reason when an email verification request fails.
 * Should be updated alongside EmailVerificationRequestResult in
 * third_party/blink/public/mojom/devtools/inspector_issue.mojom.
 */
@Serializable
public enum class EmailVerificationRequestIssueReason {
  @SerialName("InvalidEmail")
  INVALID_EMAIL,
  @SerialName("DnsFetchFailed")
  DNS_FETCH_FAILED,
  @SerialName("DnsInvalidRecord")
  DNS_INVALID_RECORD,
  @SerialName("WellKnownHttpNotFound")
  WELL_KNOWN_HTTP_NOT_FOUND,
  @SerialName("WellKnownNoResponse")
  WELL_KNOWN_NO_RESPONSE,
  @SerialName("WellKnownInvalidResponse")
  WELL_KNOWN_INVALID_RESPONSE,
  @SerialName("WellKnownListEmpty")
  WELL_KNOWN_LIST_EMPTY,
  @SerialName("WellKnownInvalidContentType")
  WELL_KNOWN_INVALID_CONTENT_TYPE,
  @SerialName("WellKnownMissingIssuanceEndpoint")
  WELL_KNOWN_MISSING_ISSUANCE_ENDPOINT,
  @SerialName("WellKnownIssuanceEndpointCrossOrigin")
  WELL_KNOWN_ISSUANCE_ENDPOINT_CROSS_ORIGIN,
  @SerialName("WellKnownUnsupportedSigningAlgorithm")
  WELL_KNOWN_UNSUPPORTED_SIGNING_ALGORITHM,
  @SerialName("TokenHttpNotFound")
  TOKEN_HTTP_NOT_FOUND,
  @SerialName("TokenNoResponse")
  TOKEN_NO_RESPONSE,
  @SerialName("TokenInvalidResponse")
  TOKEN_INVALID_RESPONSE,
  @SerialName("TokenInvalidContentType")
  TOKEN_INVALID_CONTENT_TYPE,
  @SerialName("TokenMalformedSdJwt")
  TOKEN_MALFORMED_SD_JWT,
  @SerialName("TokenInvalidSdJwt")
  TOKEN_INVALID_SD_JWT,
  @SerialName("KeyBindingSigningFailed")
  KEY_BINDING_SIGNING_FAILED,
  @SerialName("RpOriginIsOpaque")
  RP_ORIGIN_IS_OPAQUE,
  @SerialName("WellKnownMissingAccountsEndpoint")
  WELL_KNOWN_MISSING_ACCOUNTS_ENDPOINT,
  @SerialName("UserLoggedOut")
  USER_LOGGED_OUT,
  @SerialName("WellKnownAccountsEndpointCrossOrigin")
  WELL_KNOWN_ACCOUNTS_ENDPOINT_CROSS_ORIGIN,
  @SerialName("AccountsHttpNotFound")
  ACCOUNTS_HTTP_NOT_FOUND,
  @SerialName("AccountsNoResponse")
  ACCOUNTS_NO_RESPONSE,
  @SerialName("AccountsInvalidResponse")
  ACCOUNTS_INVALID_RESPONSE,
  @SerialName("AccountsInvalidContentType")
  ACCOUNTS_INVALID_CONTENT_TYPE,
  @SerialName("AccountsEmptyList")
  ACCOUNTS_EMPTY_LIST,
  @SerialName("EmailVerificationWellKnownHttpNotFound")
  EMAIL_VERIFICATION_WELL_KNOWN_HTTP_NOT_FOUND,
  @SerialName("EmailVerificationWellKnownNoResponse")
  EMAIL_VERIFICATION_WELL_KNOWN_NO_RESPONSE,
  @SerialName("EmailVerificationWellKnownInvalidResponse")
  EMAIL_VERIFICATION_WELL_KNOWN_INVALID_RESPONSE,
  @SerialName("EmailVerificationWellKnownInvalidContentType")
  EMAIL_VERIFICATION_WELL_KNOWN_INVALID_CONTENT_TYPE,
  @SerialName("JwksHttpNotFound")
  JWKS_HTTP_NOT_FOUND,
  @SerialName("JwksInvalidResponse")
  JWKS_INVALID_RESPONSE,
  @SerialName("TokenVerificationSdJwtUnsupportedHeaderAlg")
  TOKEN_VERIFICATION_SD_JWT_UNSUPPORTED_HEADER_ALG,
  @SerialName("TokenVerificationSdJwtMissingIss")
  TOKEN_VERIFICATION_SD_JWT_MISSING_ISS,
  @SerialName("TokenVerificationSdJwtMissingIat")
  TOKEN_VERIFICATION_SD_JWT_MISSING_IAT,
  @SerialName("TokenVerificationSdJwtMissingCnf")
  TOKEN_VERIFICATION_SD_JWT_MISSING_CNF,
  @SerialName("TokenVerificationSdJwtMissingEmail")
  TOKEN_VERIFICATION_SD_JWT_MISSING_EMAIL,
  @SerialName("TokenVerificationSdJwtInvalidIssuedAt")
  TOKEN_VERIFICATION_SD_JWT_INVALID_ISSUED_AT,
  @SerialName("TokenVerificationSdJwtInvalidIssuer")
  TOKEN_VERIFICATION_SD_JWT_INVALID_ISSUER,
  @SerialName("TokenVerificationSdJwtJwksMissingKeys")
  TOKEN_VERIFICATION_SD_JWT_JWKS_MISSING_KEYS,
  @SerialName("TokenVerificationSdJwtSignatureFailed")
  TOKEN_VERIFICATION_SD_JWT_SIGNATURE_FAILED,
  @SerialName("TokenVerificationSdJwtInvalidEmailVerified")
  TOKEN_VERIFICATION_SD_JWT_INVALID_EMAIL_VERIFIED,
  @SerialName("TokenVerificationSdJwtInvalidEmail")
  TOKEN_VERIFICATION_SD_JWT_INVALID_EMAIL,
  @SerialName("TokenVerificationSdJwtInvalidHolderKey")
  TOKEN_VERIFICATION_SD_JWT_INVALID_HOLDER_KEY,
  @SerialName("TokenVerificationKbInvalidTyp")
  TOKEN_VERIFICATION_KB_INVALID_TYP,
  @SerialName("TokenVerificationKbMissingAud")
  TOKEN_VERIFICATION_KB_MISSING_AUD,
  @SerialName("TokenVerificationKbMissingNonce")
  TOKEN_VERIFICATION_KB_MISSING_NONCE,
  @SerialName("TokenVerificationKbMissingIat")
  TOKEN_VERIFICATION_KB_MISSING_IAT,
  @SerialName("TokenVerificationKbMissingSdHash")
  TOKEN_VERIFICATION_KB_MISSING_SD_HASH,
  @SerialName("TokenVerificationKbInvalidIssuedAt")
  TOKEN_VERIFICATION_KB_INVALID_ISSUED_AT,
  @SerialName("TokenVerificationKbInvalidAudience")
  TOKEN_VERIFICATION_KB_INVALID_AUDIENCE,
  @SerialName("TokenVerificationKbInvalidNonce")
  TOKEN_VERIFICATION_KB_INVALID_NONCE,
  @SerialName("TokenVerificationKbInvalidSdHash")
  TOKEN_VERIFICATION_KB_INVALID_SD_HASH,
  @SerialName("TokenVerificationKbMissingCnf")
  TOKEN_VERIFICATION_KB_MISSING_CNF,
  @SerialName("TokenVerificationKbSignatureFailed")
  TOKEN_VERIFICATION_KB_SIGNATURE_FAILED,
  UNKNOWN,
}
